/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Layout;

import Model.Aluno;
import Model.Professor;
import Model.CoordenadorAdm;
import Model.CoordenadorCurso;
import Model.Funcionario;
import Model.Pessoa;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arthurfb
 */
public class Interface extends javax.swing.JFrame {

    ArrayList<Aluno> dadosAluno;
    ArrayList<Professor> dadosProfessor;
    ArrayList<CoordenadorAdm> dadosCoordenadorAdm;
    ArrayList<CoordenadorCurso> dadosCoordenadorCurso;

    public void LoadTable() {
        //Preenche a tabela do Aluno
        DefaultTableModel alunoTbl = new DefaultTableModel(new Object[]{"Nome", "RG", "Código", "Interesse",
            "CPF", "Ano Nascimento", "Sexo"}, 0);
        for (int i = 0; i < dadosAluno.size(); i++) {
            alunoTbl.addRow(new Object[]{dadosAluno.get(i).getCodigo(), dadosAluno.get(i).getInteresse(), dadosAluno.get(i).getNome(),
                dadosAluno.get(i).getRg(), dadosAluno.get(i).getCpf(), dadosAluno.get(i).getAnoNasc(), dadosAluno.get(i).getSexo()});
        }
        //Preenche a tabela do Professor
        DefaultTableModel professorTbl = new DefaultTableModel(new Object[]{"Matrícula", "Setor", "Cargo", "Formação",
            "Nível", "Disciplinas"}, 0);
        DefaultTableModel coordAdmTbl = new DefaultTableModel(new Object[]{"Matrícula", "Setor", "Cargo", "Área",
            "Plus Salário"}, 0);
        DefaultTableModel coordCursoTbl = new DefaultTableModel(new Object[]{"Matrícula", "Setor", "Cargo", "Área",
            "Plus Salário"}, 0);

        tabela_aluno.setModel(null);
        tabela_professor.setModel(null);
        tabela_coord_adm.setModel(null);
        tabela_coord_curso.setModel(null);

    }

    /**
     * Creates new form Funcionario
     */
    public Interface() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_aluno = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        t_aluno_codigo = new javax.swing.JLabel();
        c_aluno_codigo = new javax.swing.JTextField();
        t_aluno_interesse = new javax.swing.JLabel();
        c_aluno_interesse = new javax.swing.JTextField();
        t_aluno_nome = new javax.swing.JLabel();
        c_aluno_nome = new javax.swing.JTextField();
        t_aluno_rg = new javax.swing.JLabel();
        c_aluno_rg = new javax.swing.JTextField();
        t_aluno_cpf = new javax.swing.JLabel();
        c_aluno_cpf = new javax.swing.JTextField();
        t_aluno_nasc = new javax.swing.JLabel();
        c_aluno_nasc = new javax.swing.JTextField();
        t_aluno_sexo = new javax.swing.JLabel();
        c_aluno_sexo = new javax.swing.JTextField();
        btn_aluno_salvar = new javax.swing.JButton();
        aluno_btn_excluir4 = new javax.swing.JButton();
        btn_aluno_edit4 = new javax.swing.JButton();
        btn_aluno_add = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela_professor = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        t_professor_matricula = new javax.swing.JLabel();
        c_professor_matricula = new javax.swing.JTextField();
        t_professor_setor = new javax.swing.JLabel();
        c_professor_setor = new javax.swing.JTextField();
        t_professor_cargp = new javax.swing.JLabel();
        c_professor_cargo = new javax.swing.JTextField();
        t_professor_formacao = new javax.swing.JLabel();
        c_professor_formacao = new javax.swing.JTextField();
        t_professor_nivel = new javax.swing.JLabel();
        c_professor_nivel = new javax.swing.JTextField();
        t_professor_disciplinas = new javax.swing.JLabel();
        c_professor_disciplina = new javax.swing.JTextField();
        btn_professor_salvar = new javax.swing.JButton();
        t_professor_nome = new javax.swing.JLabel();
        t_professor_rg = new javax.swing.JLabel();
        t_professor_cpf = new javax.swing.JLabel();
        t_professor_anoNasc = new javax.swing.JLabel();
        t_professor_sexo = new javax.swing.JLabel();
        c_professor_nome = new javax.swing.JTextField();
        c_professor_rg = new javax.swing.JTextField();
        c_professor_cpf = new javax.swing.JTextField();
        c_professor_nasc = new javax.swing.JTextField();
        c_professor_sexo = new javax.swing.JTextField();
        aluno_btn_excluir1 = new javax.swing.JButton();
        btn_aluno_edit1 = new javax.swing.JButton();
        btn_professor_add = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabela_coord_adm = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        btn_coordadm_salvar = new javax.swing.JButton();
        c_professor_sexo1 = new javax.swing.JTextField();
        t_professor_sexo1 = new javax.swing.JLabel();
        t_professor_anoNasc1 = new javax.swing.JLabel();
        c_professor_nasc1 = new javax.swing.JTextField();
        c_professor_cpf1 = new javax.swing.JTextField();
        t_professor_cpf1 = new javax.swing.JLabel();
        t_professor_rg1 = new javax.swing.JLabel();
        c_professor_rg1 = new javax.swing.JTextField();
        c_professor_nome1 = new javax.swing.JTextField();
        t_professor_nome1 = new javax.swing.JLabel();
        aluno_btn_excluir2 = new javax.swing.JButton();
        btn_aluno_edit2 = new javax.swing.JButton();
        btn_coordadm_add = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabela_coord_curso = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        btn_coordcurso_salvar = new javax.swing.JButton();
        jTextField29 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        t_professor_sexo2 = new javax.swing.JLabel();
        c_professor_sexo2 = new javax.swing.JTextField();
        c_professor_nasc2 = new javax.swing.JTextField();
        t_professor_anoNasc2 = new javax.swing.JLabel();
        t_professor_cpf2 = new javax.swing.JLabel();
        c_professor_cpf2 = new javax.swing.JTextField();
        c_professor_rg2 = new javax.swing.JTextField();
        t_professor_rg2 = new javax.swing.JLabel();
        t_professor_nome2 = new javax.swing.JLabel();
        c_professor_nome2 = new javax.swing.JTextField();
        aluno_btn_excluir3 = new javax.swing.JButton();
        btn_aluno_edit3 = new javax.swing.JButton();
        btn_coordcurso_add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabela_aluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Interesse", "Nome", "RG", "CPF", "Ano Nasc.", "Sexo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela_aluno);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Cadastro"));

        t_aluno_codigo.setText("Código:");

        c_aluno_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_aluno_codigoActionPerformed(evt);
            }
        });

        t_aluno_interesse.setText("Interesse:");

        t_aluno_nome.setText("Nome:");

        t_aluno_rg.setText("RG:");

        t_aluno_cpf.setText("CPF:");

        t_aluno_nasc.setText("Ano Nasc.:");

        t_aluno_sexo.setText("Sexo:");

        btn_aluno_salvar.setText("Salvar");
        btn_aluno_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aluno_salvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(t_aluno_nasc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_aluno_nasc))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t_aluno_interesse)
                                    .addComponent(t_aluno_codigo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(c_aluno_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c_aluno_interesse, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(t_aluno_nome)
                                .addGap(27, 27, 27)
                                .addComponent(c_aluno_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(t_aluno_rg)
                                .addGap(44, 44, 44)
                                .addComponent(c_aluno_rg))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(t_aluno_cpf)
                                .addGap(38, 38, 38)
                                .addComponent(c_aluno_cpf))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(t_aluno_sexo)
                                .addGap(34, 34, 34)
                                .addComponent(c_aluno_sexo))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btn_aluno_salvar)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_aluno_codigo)
                    .addComponent(c_aluno_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_aluno_interesse)
                    .addComponent(c_aluno_interesse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_aluno_nome)
                    .addComponent(c_aluno_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_aluno_rg)
                    .addComponent(c_aluno_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_aluno_cpf)
                    .addComponent(c_aluno_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_aluno_nasc)
                    .addComponent(c_aluno_nasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_aluno_sexo)
                    .addComponent(c_aluno_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_aluno_salvar))
        );

        aluno_btn_excluir4.setText("Excluir");

        btn_aluno_edit4.setText("Editar");
        btn_aluno_edit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aluno_edit4ActionPerformed(evt);
            }
        });

        btn_aluno_add.setText("Adicionar");
        btn_aluno_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aluno_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_aluno_add, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btn_aluno_edit4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(aluno_btn_excluir4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aluno_add)
                    .addComponent(btn_aluno_edit4)
                    .addComponent(aluno_btn_excluir4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        jTabbedPane1.addTab("Aluno", jPanel1);

        tabela_professor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Matrícula", "Setor", "Cargo", "Formação", "Nível", "Dísciplinas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabela_professor);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Cadastro"));

        t_professor_matricula.setText("Matrícula:");

        t_professor_setor.setText("Setor:");

        t_professor_cargp.setText("Cargo:");

        t_professor_formacao.setText("Formação:");

        t_professor_nivel.setText("Nível:");

        t_professor_disciplinas.setText("Disciplina:");

        btn_professor_salvar.setText("Salvar");

        t_professor_nome.setText("Nome:");

        t_professor_rg.setText("RG:");

        t_professor_cpf.setText("CPF:");

        t_professor_anoNasc.setText("Ano Nasc.:");

        t_professor_sexo.setText("Sexo:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(btn_professor_salvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_professor_matricula)
                    .addComponent(t_professor_setor)
                    .addComponent(t_professor_cargp)
                    .addComponent(t_professor_formacao)
                    .addComponent(t_professor_nivel)
                    .addComponent(t_professor_disciplinas)
                    .addComponent(t_professor_anoNasc)
                    .addComponent(t_professor_sexo)
                    .addComponent(t_professor_nome)
                    .addComponent(t_professor_cpf)
                    .addComponent(t_professor_rg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(c_professor_nivel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(c_professor_formacao, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c_professor_cargo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c_professor_setor, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c_professor_matricula, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c_professor_nome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c_professor_rg, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c_professor_cpf, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c_professor_sexo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c_professor_nasc, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c_professor_disciplina))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_professor_nome)
                    .addComponent(c_professor_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_professor_rg)
                    .addComponent(c_professor_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_professor_cpf)
                    .addComponent(c_professor_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_professor_anoNasc)
                    .addComponent(c_professor_nasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_professor_sexo)
                    .addComponent(c_professor_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_professor_matricula)
                    .addComponent(c_professor_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_professor_setor)
                    .addComponent(c_professor_setor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_professor_cargp)
                    .addComponent(c_professor_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_professor_formacao)
                    .addComponent(c_professor_formacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_professor_nivel)
                    .addComponent(c_professor_nivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_professor_disciplinas)
                    .addComponent(c_professor_disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(btn_professor_salvar))
        );

        aluno_btn_excluir1.setText("Excluir");

        btn_aluno_edit1.setText("Editar");
        btn_aluno_edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aluno_edit1ActionPerformed(evt);
            }
        });

        btn_professor_add.setText("Adicionar");
        btn_professor_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_professor_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_professor_add, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btn_aluno_edit1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(aluno_btn_excluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_professor_add)
                    .addComponent(btn_aluno_edit1)
                    .addComponent(aluno_btn_excluir1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Professor", jPanel3);

        tabela_coord_adm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Matrícula", "Setor", "Cargo", "Área", "Plus Salário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabela_coord_adm);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Cadastro"));

        jLabel15.setText("jLabel1");

        jLabel16.setText("jLabel2");

        jLabel17.setText("jLabel3");

        jLabel18.setText("jLabel4");

        jLabel19.setText("jLabel5");

        jLabel20.setText("jLabel6");

        jLabel21.setText("jLabel7");

        btn_coordadm_salvar.setText("Salvar");

        t_professor_sexo1.setText("Sexo:");

        t_professor_anoNasc1.setText("Ano Nasc.:");

        t_professor_cpf1.setText("CPF:");

        t_professor_rg1.setText("RG:");

        t_professor_nome1.setText("Nome:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btn_coordadm_salvar))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_professor_anoNasc1)
                            .addComponent(t_professor_sexo1)
                            .addComponent(t_professor_nome1)
                            .addComponent(t_professor_cpf1)
                            .addComponent(t_professor_rg1)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField20, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField19, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField17, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField16, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField15, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_professor_nome1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_professor_rg1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_professor_cpf1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_professor_sexo1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_professor_nasc1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(jTextField18, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField21))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_professor_nome1)
                    .addComponent(c_professor_nome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_professor_rg1)
                    .addComponent(c_professor_rg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_professor_cpf1)
                    .addComponent(c_professor_cpf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_professor_anoNasc1)
                    .addComponent(c_professor_nasc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_professor_sexo1)
                    .addComponent(c_professor_sexo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(btn_coordadm_salvar))
        );

        aluno_btn_excluir2.setText("Excluir");

        btn_aluno_edit2.setText("Editar");
        btn_aluno_edit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aluno_edit2ActionPerformed(evt);
            }
        });

        btn_coordadm_add.setText("Adicionar");
        btn_coordadm_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_coordadm_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btn_coordadm_add, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btn_aluno_edit2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(aluno_btn_excluir2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_coordadm_add)
                    .addComponent(btn_aluno_edit2)
                    .addComponent(aluno_btn_excluir2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        jTabbedPane1.addTab("Coord. Adm.", jPanel4);

        tabela_coord_curso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Matrícula", "Setor", "Cargo", "Área", "Plus Salário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tabela_coord_curso);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Cadastro"));

        btn_coordcurso_salvar.setText("Salvar");

        jLabel29.setText("jLabel7");

        jLabel30.setText("jLabel6");

        jLabel31.setText("jLabel5");

        jLabel32.setText("jLabel4");

        jLabel33.setText("jLabel3");

        jLabel34.setText("jLabel2");

        jLabel35.setText("jLabel1");

        t_professor_sexo2.setText("Sexo:");

        t_professor_anoNasc2.setText("Ano Nasc.:");

        t_professor_cpf2.setText("CPF:");

        t_professor_rg2.setText("RG:");

        t_professor_nome2.setText("Nome:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btn_coordcurso_salvar))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_professor_anoNasc2)
                            .addComponent(t_professor_sexo2)
                            .addComponent(t_professor_nome2)
                            .addComponent(t_professor_cpf2)
                            .addComponent(t_professor_rg2)
                            .addComponent(jLabel35)
                            .addComponent(jLabel34)
                            .addComponent(jLabel33)
                            .addComponent(jLabel32)
                            .addComponent(jLabel31)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField30, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField31, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField33, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField34, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField35, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_professor_nome2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_professor_rg2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_professor_cpf2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_professor_sexo2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_professor_nasc2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField32, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_professor_nome2)
                    .addComponent(c_professor_nome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_professor_rg2)
                    .addComponent(c_professor_rg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_professor_cpf2)
                    .addComponent(c_professor_cpf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_professor_anoNasc2)
                    .addComponent(c_professor_nasc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_professor_sexo2)
                    .addComponent(c_professor_sexo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(btn_coordcurso_salvar))
        );

        aluno_btn_excluir3.setText("Excluir");

        btn_aluno_edit3.setText("Editar");
        btn_aluno_edit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aluno_edit3ActionPerformed(evt);
            }
        });

        btn_coordcurso_add.setText("Adicionar");
        btn_coordcurso_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_coordcurso_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btn_coordcurso_add, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btn_aluno_edit3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(aluno_btn_excluir3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_coordcurso_add)
                    .addComponent(btn_aluno_edit3)
                    .addComponent(aluno_btn_excluir3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Coord. Curso.", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c_aluno_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_aluno_codigoActionPerformed

    }//GEN-LAST:event_c_aluno_codigoActionPerformed

    private void btn_aluno_edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aluno_edit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_aluno_edit1ActionPerformed

    private void btn_professor_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_professor_addActionPerformed

    }//GEN-LAST:event_btn_professor_addActionPerformed

    private void btn_aluno_edit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aluno_edit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_aluno_edit2ActionPerformed

    private void btn_coordadm_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_coordadm_addActionPerformed

    }//GEN-LAST:event_btn_coordadm_addActionPerformed

    private void btn_aluno_edit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aluno_edit3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_aluno_edit3ActionPerformed

    private void btn_coordcurso_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_coordcurso_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_coordcurso_addActionPerformed

    private void btn_aluno_edit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aluno_edit4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_aluno_edit4ActionPerformed

    private void btn_aluno_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aluno_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_aluno_addActionPerformed

    private void btn_aluno_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aluno_salvarActionPerformed
        Aluno a = new Aluno();
        LoadTable();
    }//GEN-LAST:event_btn_aluno_salvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aluno_btn_excluir1;
    private javax.swing.JButton aluno_btn_excluir2;
    private javax.swing.JButton aluno_btn_excluir3;
    private javax.swing.JButton aluno_btn_excluir4;
    private javax.swing.JButton btn_aluno_add;
    private javax.swing.JButton btn_aluno_edit1;
    private javax.swing.JButton btn_aluno_edit2;
    private javax.swing.JButton btn_aluno_edit3;
    private javax.swing.JButton btn_aluno_edit4;
    private javax.swing.JButton btn_aluno_salvar;
    private javax.swing.JButton btn_coordadm_add;
    private javax.swing.JButton btn_coordadm_salvar;
    private javax.swing.JButton btn_coordcurso_add;
    private javax.swing.JButton btn_coordcurso_salvar;
    private javax.swing.JButton btn_professor_add;
    private javax.swing.JButton btn_professor_salvar;
    private javax.swing.JTextField c_aluno_codigo;
    private javax.swing.JTextField c_aluno_cpf;
    private javax.swing.JTextField c_aluno_interesse;
    private javax.swing.JTextField c_aluno_nasc;
    private javax.swing.JTextField c_aluno_nome;
    private javax.swing.JTextField c_aluno_rg;
    private javax.swing.JTextField c_aluno_sexo;
    private javax.swing.JTextField c_professor_cargo;
    private javax.swing.JTextField c_professor_cpf;
    private javax.swing.JTextField c_professor_cpf1;
    private javax.swing.JTextField c_professor_cpf2;
    private javax.swing.JTextField c_professor_disciplina;
    private javax.swing.JTextField c_professor_formacao;
    private javax.swing.JTextField c_professor_matricula;
    private javax.swing.JTextField c_professor_nasc;
    private javax.swing.JTextField c_professor_nasc1;
    private javax.swing.JTextField c_professor_nasc2;
    private javax.swing.JTextField c_professor_nivel;
    private javax.swing.JTextField c_professor_nome;
    private javax.swing.JTextField c_professor_nome1;
    private javax.swing.JTextField c_professor_nome2;
    private javax.swing.JTextField c_professor_rg;
    private javax.swing.JTextField c_professor_rg1;
    private javax.swing.JTextField c_professor_rg2;
    private javax.swing.JTextField c_professor_setor;
    private javax.swing.JTextField c_professor_sexo;
    private javax.swing.JTextField c_professor_sexo1;
    private javax.swing.JTextField c_professor_sexo2;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JLabel t_aluno_codigo;
    private javax.swing.JLabel t_aluno_cpf;
    private javax.swing.JLabel t_aluno_interesse;
    private javax.swing.JLabel t_aluno_nasc;
    private javax.swing.JLabel t_aluno_nome;
    private javax.swing.JLabel t_aluno_rg;
    private javax.swing.JLabel t_aluno_sexo;
    private javax.swing.JLabel t_professor_anoNasc;
    private javax.swing.JLabel t_professor_anoNasc1;
    private javax.swing.JLabel t_professor_anoNasc2;
    private javax.swing.JLabel t_professor_cargp;
    private javax.swing.JLabel t_professor_cpf;
    private javax.swing.JLabel t_professor_cpf1;
    private javax.swing.JLabel t_professor_cpf2;
    private javax.swing.JLabel t_professor_disciplinas;
    private javax.swing.JLabel t_professor_formacao;
    private javax.swing.JLabel t_professor_matricula;
    private javax.swing.JLabel t_professor_nivel;
    private javax.swing.JLabel t_professor_nome;
    private javax.swing.JLabel t_professor_nome1;
    private javax.swing.JLabel t_professor_nome2;
    private javax.swing.JLabel t_professor_rg;
    private javax.swing.JLabel t_professor_rg1;
    private javax.swing.JLabel t_professor_rg2;
    private javax.swing.JLabel t_professor_setor;
    private javax.swing.JLabel t_professor_sexo;
    private javax.swing.JLabel t_professor_sexo1;
    private javax.swing.JLabel t_professor_sexo2;
    private javax.swing.JTable tabela_aluno;
    private javax.swing.JTable tabela_coord_adm;
    private javax.swing.JTable tabela_coord_curso;
    private javax.swing.JTable tabela_professor;
    // End of variables declaration//GEN-END:variables
}
